apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
networking:
  podSubnet: 192.168.0.0/16
kubernetesVersion: v1.10.2
featureGates:
    CoreDNS: true
imageRepository: reg.qiqiu.com/k8s
ImagePullPolicy: "IfNotPresent"

