
---
apiVersion: v1
kind: Pod
metadata:
  name: registry
  labels:
    app: registry
  namespace: default
spec:
  containers:
  - name: registry
    image: docker.io/registry:2.6.2
    imagePullPolicy: Always
    ports:
      - containerPort: 5000
        protocol: TCP

---
# ------------------- Dashboard Service ------------------- #
kind: Service
apiVersion: v1
metadata:
  labels:
    app: registry
  name: registry
  namespace: default
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: registry
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry-http-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: registry
          servicePort: 5000